import { copyFileSync, existsSync, linkSync } from "node:fs";
import { mkdtemp, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import process from "node:process";
import { fileURLToPath, pathToFileURL } from "node:url";
import type { MockBinScriptFile } from "./mock-bin.js";
import { MOCKS_VAR } from "./mock-bin-env.js";
import type { MocksEnv, MockTarget } from "./mock-bin-runtime.js";
import { resolveTsxImportUrl } from "./mock-bin-tsx.js";
import { rmScratch } from "./rm-scratch.js";

// Windows twin of the POSIX mockBin: PATH interception needs a real
// executable there (node refuses to spawn .cmd/.bat shims without a
// shell, and an extensionless #! script cannot execute at all). Each
// mock is a copy of a tiny native trampoline (native/trampoline.c)
// named <bin>.exe. The trampoline launches Node with a generated
// bootstrap as the script and the invoked mock plus the original argv
// as plain arguments — so leading flags, quotes, and line breaks reach
// the mock verbatim instead of being parsed by Node's own CLI parser
// (the limitation of the previous node.exe-hardlink mechanism). The
// bootstrap dispatches through mock-bin-runtime; argv, stdin, stdout,
// stderr, and exit codes all pass through. The registry travels in the
// env var named by MOCKS_VAR; mock-bin-runtime keeps its own copy of
// the name, so the two must stay in sync.
const HELPER_NAME = "mock-a-bin-run-original";

// The Node executable to launch, recorded when the mock is installed
// and read by the native trampoline (which also owns its name).
const NODE_EXE_VAR = "TYPE_A_BIN_NODE_EXE";

// Temporary escape hatch: set to "1" to force the legacy node.exe
// hard-link shims plus the NODE_OPTIONS preload while the trampoline
// rollout is validated. Removed once both Windows architectures are
// covered.
const DISABLE_TRAMPOLINE_VAR = "TYPE_A_BIN_DISABLE_TRAMPOLINE";

const TRAMPOLINE_NAME = "type-a-bin-trampoline.exe";
const BOOTSTRAP_NAME = "mock-bin-trampoline.cjs";

// The dispatch module ships next to this one: mock-bin-runtime.js in
// the published dist build, mock-bin-runtime.ts when running from
// source (node's native type stripping loads the .ts form in child
// processes).
const ownPath = fileURLToPath(import.meta.url);
const runtimeUrl = pathToFileURL(
  path.join(path.dirname(ownPath), `mock-bin-runtime${path.extname(ownPath)}`),
).href;

// The preload ships the same way and remains the fallback mechanism.
const preloadPath = path.join(
  path.dirname(ownPath),
  `mock-bin-preload${path.extname(ownPath)}`,
);

/**
 * Locates the checked-in trampoline launcher for this platform: the
 * copy under `dist/native` in the published package first, the source
 * checkout's `native/bin` second (tests running before a build). Both
 * supported Windows architectures ship prebuilt; anything else falls
 * back to the legacy shims.
 */
const trampolineSourcePath = (): string | null => {
  if (process.platform !== "win32") return null;
  if (process.arch !== "x64" && process.arch !== "arm64") return null;

  const ownDir = path.dirname(ownPath);
  const candidates = [
    path.join(ownDir, "native", "win32", process.arch, TRAMPOLINE_NAME),
    path.join(
      path.dirname(ownDir),
      "native",
      "bin",
      "win32",
      process.arch,
      TRAMPOLINE_NAME,
    ),
  ];
  return candidates.find((candidate) => existsSync(candidate)) ?? null;
};

/**
 * The bootstrap the native trampoline runs: Node's main module, whose
 * only job is handing the invoked mock and the original argv to the
 * shared dispatch in mock-bin-runtime.
 */
const bootstrapCode = (url: string): string =>
  `// Generated by type-a-bin: the Windows trampoline launcher starts\n` +
  `// Node with this script, passing the invoked mock and the original\n` +
  `// argv as plain arguments.\n` +
  `import(${JSON.stringify(url)}).then((runtime) =>\n` +
  `  runtime.runTrampoline(),\n);\n`;

const readMocks = (): MocksEnv => {
  try {
    return JSON.parse(process.env[MOCKS_VAR] ?? "{}") as MocksEnv;
  } catch {
    return {};
  }
};

const restoreEnv = (name: string, previous: string | undefined): void => {
  if (previous === undefined) delete process.env[name];
  else process.env[name] = previous;
};

/** Hard links node.exe as `destination`, copying across volume boundaries. */
const linkNodeExecutable = (destination: string): void => {
  try {
    linkSync(process.execPath, destination);
  } catch {
    // Different volume than the node install: fall back to a real copy.
    copyFileSync(process.execPath, destination);
  }
};

/**
 * Splits an interpreter string into words, accepting both a bare name
 * ("bash"), a full shebang ("#!/usr/bin/env bash"), or an absolute
 * shebang path ("#!/bin/bash").
 */
const toInterpreterWords = (shebang: string): string[] =>
  shebang
    .replace(/^#!\s*/, "")
    .replace(/^\/(?:usr\/)?bin\/env\s+/, "")
    .trim()
    .split(/\s+/)
    .filter((word) => word !== "");

const basenameWithoutExecutableExtension = (word: string): string =>
  path.basename(word).replace(/\.(?:bat|cmd|com|exe)$/iu, "");

const isNodeInterpreter = (words: string[]): boolean =>
  basenameWithoutExecutableExtension(words[0] ?? "").toLowerCase() === "node";

const interpreterExecutableName = (word: string | undefined): string =>
  word === undefined ? "bash" : basenameWithoutExecutableExtension(word);

// A `--import` word names tsx when it is the bare package ("tsx",
// "tsx/cjs") or a file URL resolving into it — the script-file
// shorthand embeds an absolute loader URL.
const isTsxImport = (word: string): boolean => {
  if (word === "tsx" || word.startsWith("tsx/")) return true;
  if (!word.startsWith("file:")) return false;
  try {
    return fileURLToPath(word).split(/[\\/]/).includes("tsx");
  } catch {
    return false;
  }
};

const toShebangLine = (interpreter: string): string =>
  interpreter.startsWith("#!") ? interpreter : `#!/usr/bin/env ${interpreter}`;

/**
 * Builds the CommonJS mock for the output shorthand. bash `echo` expands
 * positional parameters, so the Node twin expands `$1`..`$9`, `$*`, and
 * `$@` from the command line to keep the shorthand's behaviour aligned.
 */
const echoScript = (output: string): string => `
const args = process.argv.slice(2);
const expand = (text) =>
  text
    .replace(/\\$[@*]/g, args.join(" "))
    .replace(/\\$(\\d)/g, (_, digit) => args[Number(digit) - 1] ?? "");
console.log(expand(${JSON.stringify(output)}));
`;

const assertScriptFile = async (file: string): Promise<void> => {
  const stats = await stat(file).catch(() => null);
  if (!stats?.isFile())
    throw new Error(`mockBin: script file not found: ${file}`);
};

/** Copies the trampoline launcher into the mock directory. */
const installTrampoline = async (
  tempDir: string,
  binBase: string,
  source: string,
): Promise<void> => {
  copyFileSync(source, path.join(tempDir, `${binBase}.exe`));
  copyFileSync(source, path.join(tempDir, `${HELPER_NAME}.exe`));
  await writeFile(
    path.join(tempDir, BOOTSTRAP_NAME),
    bootstrapCode(runtimeUrl),
  );
};

/**
 * Writes the mock's entry script into the mock directory and returns
 * its path. Script files keep their real extension so extension-aware
 * loaders (e.g. node --import tsx) parse them; inline node code runs as
 * CommonJS, matching the extensionless scripts the POSIX implementation
 * writes; other interpreters get a shebang script.
 */
const writeMockEntry = async (
  tempDir: string,
  binBase: string,
  shebangOrOutput: string,
  codeOrScript: string | MockBinScriptFile | undefined,
  isNodeMock: boolean,
): Promise<string> => {
  if (typeof codeOrScript === "object") return path.resolve(codeOrScript.file);
  if (isNodeMock) {
    const entry = path.join(tempDir, `${binBase}-mock.cjs`);
    const code = codeOrScript ?? echoScript(shebangOrOutput);
    await writeFile(entry, `${code}\n`);
    return entry;
  }
  const entry = path.join(tempDir, `${binBase}-mock.sh`);
  await writeFile(
    entry,
    `${toShebangLine(shebangOrOutput)}\n${codeOrScript}\n`,
  );
  return entry;
};

// Prepends --import flags ahead of a previous NODE_OPTIONS value so
// the preload chain runs first in spawned processes.
const importsAheadOf = (
  imports: string[],
  previous: string | undefined,
): string => {
  const prepended = imports.join(" ");
  return previous === undefined || previous === ""
    ? prepended
    : `${prepended} ${previous}`;
};

/**
 * Windows implementation of `mockBin`; see mock-bin.ts for the public
 * overloads. By default it installs copies of the trampoline launcher
 * as `<binName>.exe` and the `mock-a-bin-run-original.exe` helper plus
 * a generated bootstrap into a temp directory prepended to PATH, and
 * registers the mock in the dispatch registry. Setting
 * TYPE_A_BIN_DISABLE_TRAMPOLINE=1 (or a missing launcher) falls back to
 * the legacy node.exe hard links with the NODE_OPTIONS preload.
 */
const mockBinWindows = async (
  binName: string,
  pattern: string | undefined,
  shebangOrOutput: string,
  codeOrScript: string | MockBinScriptFile | undefined,
): Promise<() => void> => {
  if (typeof codeOrScript === "object")
    await assertScriptFile(codeOrScript.file);

  const originalPath = process.env.PATH ?? "";
  const previousNodeOptions = process.env.NODE_OPTIONS;
  const previousMocks = process.env[MOCKS_VAR];
  const previousNodeExe = process.env[NODE_EXE_VAR];

  // A binName already carrying .exe stays a valid executable name while
  // the registry key matches the shim's argv[0] basename.
  const binBase = binName.replace(/\.exe$/iu, "");
  const tempDir = await mkdtemp(path.join(tmpdir(), "mock-bin-"));

  const trampolineSource =
    process.env[DISABLE_TRAMPOLINE_VAR] === "1" ? null : trampolineSourcePath();
  // The null case falls back to the legacy node.exe hard links.
  if (trampolineSource !== null)
    await installTrampoline(tempDir, binBase, trampolineSource);
  else {
    linkNodeExecutable(path.join(tempDir, `${binBase}.exe`));
    linkNodeExecutable(path.join(tempDir, `${HELPER_NAME}.exe`));
  }

  const words =
    codeOrScript === undefined ? ["node"] : toInterpreterWords(shebangOrOutput);
  const isNodeMock = codeOrScript === undefined || isNodeInterpreter(words);

  const interpreter = isNodeMock
    ? undefined
    : interpreterExecutableName(words[0]);
  const entry = await writeMockEntry(
    tempDir,
    binBase,
    shebangOrOutput,
    codeOrScript,
    isNodeMock,
  );

  // The tsx loader is resolved to an absolute file URL up front: the
  // trampoline bootstrap imports it before a .ts entry, and the legacy
  // NODE_OPTIONS chain carries it ahead of the preload. Without tsx,
  // node's native type stripping applies.
  const scriptFile =
    typeof codeOrScript === "object" ? codeOrScript.file : undefined;
  const tsxImportUrl =
    isNodeMock && words.some(isTsxImport)
      ? resolveTsxImportUrl(scriptFile)
      : null;

  const target: MockTarget = {
    kind: isNodeMock ? "node" : "spawn",
    entry,
    ...(interpreter === undefined ? {} : { interpreter }),
    ...(pattern ? { pattern } : {}),
    ...(tsxImportUrl === null ? {} : { tsxImportUrl }),
    originalPath,
  };

  const mocks = readMocks();
  process.env[MOCKS_VAR] = JSON.stringify({
    ...mocks,
    targets: { ...mocks.targets, [binBase]: target },
    runOriginal: { binName: binBase, originalPath },
  });

  if (trampolineSource !== null) process.env[NODE_EXE_VAR] = process.execPath;
  else
    process.env.NODE_OPTIONS = importsAheadOf(
      [
        ...(tsxImportUrl === null ? [] : [`--import ${tsxImportUrl}`]),
        `--import ${pathToFileURL(preloadPath).href}`,
      ],
      previousNodeOptions,
    );

  process.env.PATH = `${tempDir}${path.delimiter}${originalPath}`;

  return (): void => {
    if (originalPath === "") delete process.env.PATH;
    else process.env.PATH = originalPath;
    restoreEnv("NODE_OPTIONS", previousNodeOptions);
    restoreEnv(MOCKS_VAR, previousMocks);
    restoreEnv(NODE_EXE_VAR, previousNodeExe);
    rmScratch(tempDir);
  };
};

export { mockBinWindows };
